/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as ApiDirectorRouteImport } from './routes/api/director'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiProductionRouteImport } from './routes/api/production'
import { Route as ApiPublicEmbedSessionRouteImport } from './routes/api/public/embed-session'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDirectorRoute = ApiDirectorRouteImport.update({
  id: '/api/director',
  path: '/api/director',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductionRoute = ApiProductionRouteImport.update({
  id: '/api/production',
  path: '/api/production',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmbedSessionRoute = ApiPublicEmbedSessionRouteImport.update({
  id: '/api/public/embed-session',
  path: '/api/public/embed-session',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/embed': typeof EmbedRoute
  '/api/director': typeof ApiDirectorRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/production': typeof ApiProductionRoute
  '/api/public/embed-session': typeof ApiPublicEmbedSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/embed': typeof EmbedRoute
  '/api/director': typeof ApiDirectorRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/production': typeof ApiProductionRoute
  '/api/public/embed-session': typeof ApiPublicEmbedSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/embed': typeof EmbedRoute
  '/api/director': typeof ApiDirectorRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/production': typeof ApiProductionRoute
  '/api/public/embed-session': typeof ApiPublicEmbedSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/embed'
    | '/api/director'
    | '/api/generate-image'
    | '/api/production'
    | '/api/public/embed-session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/embed'
    | '/api/director'
    | '/api/generate-image'
    | '/api/production'
    | '/api/public/embed-session'
  id:
    | '__root__'
    | '/'
    | '/embed'
    | '/api/director'
    | '/api/generate-image'
    | '/api/production'
    | '/api/public/embed-session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmbedRoute: typeof EmbedRoute
  ApiDirectorRoute: typeof ApiDirectorRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiProductionRoute: typeof ApiProductionRoute
  ApiPublicEmbedSessionRoute: typeof ApiPublicEmbedSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/director': {
      id: '/api/director'
      path: '/api/director'
      fullPath: '/api/director'
      preLoaderRoute: typeof ApiDirectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/production': {
      id: '/api/production'
      path: '/api/production'
      fullPath: '/api/production'
      preLoaderRoute: typeof ApiProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/embed-session': {
      id: '/api/public/embed-session'
      path: '/api/public/embed-session'
      fullPath: '/api/public/embed-session'
      preLoaderRoute: typeof ApiPublicEmbedSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmbedRoute: EmbedRoute,
  ApiDirectorRoute: ApiDirectorRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiProductionRoute: ApiProductionRoute,
  ApiPublicEmbedSessionRoute: ApiPublicEmbedSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
